version: "3.8"
services:
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    networks:
      app-network:
        aliases: [api, n.to]

  frontend:
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on: [backend]

networks:
  app-network:
    name: appnet
    driver: bridge

